### ISSUE TITLE
Order of renderer output is not fixed

### ISSUE THREAD

**Issue by htaketani** [goccy/p5-Compiler-Parser#20]
Order of renderer output is not fixed
Renderer出力の順序が一定でない

Target program (target.pl) is as follows,
解析対象とするプログラム(target.pl)を以下のように用意し

```
$ cat target.pl
$v = 1;
```

When parsing using the SYNOPSIS code (parser.pl),
SYNOPSISのコード(parser.pl)を使ってパースすると、

```
$ cat parser.pl
#!/usr/bin/env perl
use Compiler::Lexer;
use Compiler::Parser;
use Compiler::Parser::AST::Renderer;

my $filename = $ARGV[0];
open(my $fh, "<", $filename) or die("Cannot open $filename: $!");
my $script = do { local $/; <$fh> };
my $lexer  = Compiler::Lexer->new($filename);
my $tokens = $lexer->tokenize($script);
my $parser = Compiler::Parser->new();
my $ast = $parser->parse($tokens);
Compiler::Parser::AST::Renderer->new->render($ast);
```

The order of `<left>` and `<right>` may change with each execution.
実行する毎に、`<left>` と `<right>` の順序が変わることがあります。

```
$ ./parser.pl target.pl
Stmt |
-----Expr |
----------GlobalVar
----------Assign
----------Int
-----SemiColon
├── [=]
|   ├── <right> [1]
|   ├── <left> [$v]

$ ./parser.pl target.pl
Stmt |
-----Expr |
----------GlobalVar
----------Assign
----------Int
-----SemiColon
├── [=]
|   ├── <left> [$v]
|   ├── <right> [1]
```

Because it is inconvenient to see the difference,
I want to be fixed the output against to input.
出力結果の差分を見る場合などでは不便に思いますので、
入力に対して出力が変わらないようにしたいと思っています。

in Compiler::Parser::AST::Renderer::Engine::Text::__render(),
thinking that the node names were not sorted, I wrote the patch.
This patch seems to make the output unique.
How about?
Compiler::Parser::AST::Renderer::Engine::Text::__render() で、
ノード名がソートされていないことが原因と思い、パッチを書きました。
この修正で出力を一定にすることができたように思いますが、
どうでしょうか？

**Comment by htaketani** [comment]
I'm sorry I made a mistake.
The first commit `ae94a89` was a mistake (incorrect comment), and PullReq deleted.
The second commit `ee053ca` is correct.
すみません、間違えました。
1つ目のコミットは間違い(コメント間違え)でした。PullReqも削除しました。
2つ目のコミットが正しいものです。

**Comment by goccy** [comment]
resolve by #22
